/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/cocos2d/CCDrawingPrimitives.h File Reference
#import <Foundation/Foundation.h>
*
#import `ccTypes.h`
*
#import `ccMacros.h`
*
Functions
void ccDrawPoint (CGPoint point)
void ccDrawPoints (const CGPoint *points, NSUInteger numberOfPoints)
void ccDrawLine (CGPoint origin, CGPoint destination)
void ccDrawRect (CGPoint origin, CGPoint destination)
void ccDrawSolidRect (CGPoint origin, CGPoint destination, ccColor4F color)
void ccDrawPoly (const CGPoint *vertices, NSUInteger numOfVertices, BOOL closePolygon)
void ccDrawSolidPoly (const CGPoint *poli, NSUInteger numberOfPoints, ccColor4F color)
void ccDrawCircle (CGPoint center, float radius, float angle, NSUInteger segments, BOOL drawLineToCenter)
void ccDrawQuadBezier (CGPoint origin, CGPoint control, CGPoint destination, NSUInteger segments)
void ccDrawCubicBezier (CGPoint origin, CGPoint control1, CGPoint control2, CGPoint destination, NSUInteger segments)
void ccDrawCatmullRom (CCPointArray *arrayOfControlPoints, NSUInteger segments)
void ccDrawCardinalSpline (CCPointArray *config, CGFloat tension, NSUInteger segments)
void ccDrawColor4B (GLubyte r, GLubyte g, GLubyte b, GLubyte a)
void ccDrawColor4F (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
void ccPointSize (GLfloat pointSize)
Detailed Description
Drawing OpenGL ES primitives.
ccDrawPoint, ccDrawPoints
ccDrawLine
ccDrawRect, ccDrawSolidRect
ccDrawPoly, ccDrawSolidPoly
ccDrawCircle
ccDrawQuadBezier
ccDrawCubicBezier
ccDrawCatmullRom
ccDrawCardinalSpline
You can change the color, point size, width by calling:
ccDrawColor4B(), ccDrawColor4F()
ccPointSize()
glLineWidth()
Warning
These functions draws the Line, Point, Polygon, immediately. They aren't batched. If you are going to make a game that depends on these primitives, I suggest creating a batch. Instead you should use CCDrawNode
Function Documentation
void ccDrawCardinalSpline (CCPointArray * config, CGFloat tension, NSUInteger segments)
draws a Cardinal Spline path.
Warning
This function could be pretty slow. Use it only for debugging purposes.
Since
v2.0
Referenced by ccDrawCardinalSpline(), and ccDrawCatmullRom().
        lazy_init();
        
        ccVertex2F vertices[segments + 1];
        NSUInteger p;
        CGFloat lt;
        CGFloat deltaT = 1.0 / [config count];
        
        for(NSUInteger i=0; i < segments+1;i++)
                
                CGFloat dt = (CGFloat)i / segments;
        
                // border
                if(dt == 1)
                        p = [config count] - 1;
                        lt = 1;
                 else
                        p = dt / deltaT;
                        lt = (dt - deltaT * (CGFloat)p) / deltaT;
                
                
                // Interpolate
                CGPoint pp0 = [config getControlPointAtIndex:p-1];
                CGPoint pp1 = [config getControlPointAtIndex:p+0];
                CGPoint pp2 = [config getControlPointAtIndex:p+1];
                CGPoint pp3 = [config getControlPointAtIndex:p+2];
                
                CGPoint newPos = ccCardinalSplineAt(pp0, pp1, pp2, pp3,
      tension, lt);
                vertices[i].x = newPos.x;
                vertices[i].y = newPos.y;
        
        
        [shader_ use];
        [shader_ setUniformsForBuiltins];
        [shader_ setUniformLocation:colorLocation_ with4fv:(GLfloat*) &color_.r
       count:1];
        
        ccGLEnableVertexAttribs(kCCVertexAttribFlag_Position);
        
        glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT, GL_FALSE,
      0, vertices);
        glDrawArrays(GL_LINE_STRIP, 0, (GLsizei) segments + 1);
        
        CC_INCREMENT_GL_DRAWS(1);
void ccDrawCatmullRom (CCPointArray * arrayOfControlPoints, NSUInteger segments)
draws a Catmull Rom path.
Warning
This function could be pretty slow. Use it only for debugging purposes.
Since
v2.0
Referenced by ccDrawCatmullRom().
        ccDrawCardinalSpline(points, 0.5f, segments);
void ccDrawCircle (CGPoint center, float radius, float angle, NSUInteger segments, BOOL drawLineToCenter)
draws a circle given the center, radius and number of segments measured in points
Referenced by ccDrawCircle().
        lazy_init();
        int additionalSegment = 1;
        if (drawLineToCenter)
                additionalSegment++;
        const float coef = 2.0f * (float)M_PI/segs;
        GLfloat *vertices = calloc(sizeof(GLfloat)*2*(segs+2), 1);
        if(! vertices)
                return;
        for(NSUInteger i = 0;i <= segs; i++)
                float rads = i*coef;
                GLfloat j = r * cosf(rads + a) + center.x;
                GLfloat k = r * sinf(rads + a) + center.y;
                vertices[i*2] = j;
                vertices[i*2+1] = k;
        
        vertices[(segs+1)*2] = center.x;
        vertices[(segs+1)*2+1] = center.y;
        [shader_ use];
        [shader_ setUniformsForBuiltins];
        [shader_ setUniformLocation:colorLocation_ with4fv:(GLfloat*) &color_.r
       count:1];
        ccGLEnableVertexAttribs(kCCVertexAttribFlag_Position);
        glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT, GL_FALSE,
      0, vertices);
        glDrawArrays(GL_LINE_STRIP, 0, (GLsizei) segs+additionalSegment);
        free(vertices);
        
        CC_INCREMENT_GL_DRAWS(1);
void ccDrawColor4B (GLubyte r, GLubyte g, GLubyte b, GLubyte a)
set the drawing color with 4 unsigned bytes
Since
v2.0
Referenced by ccDrawColor4B().
        color_ = (ccColor4F) r/255.0f, g/255.0f, b/255.0f, a/255.0f;
void ccDrawColor4F (GLfloat r, GLfloat g, GLfloat b, GLfloat a)
set the drawing color with 4 floats
Since
v2.0
Referenced by ccDrawColor4F().
        color_ = (ccColor4F) r, g, b, a;
void ccDrawCubicBezier (CGPoint origin, CGPoint control1, CGPoint control2, CGPoint destination, NSUInteger segments)
draws a cubic bezier path measured in points.
Warning
This function could be pretty slow. Use it only for debugging purposes.
Since
v0.8
Referenced by ccDrawCubicBezier().
        lazy_init();
        ccVertex2F vertices[segments + 1];
        float t = 0;
        for(NSUInteger i = 0; i < segments; i++)
        
                vertices[i].x = powf(1 - t, 3) * origin.x + 3.0f * powf(1 - t,
      2) * t * control1.x + 3.0f * (1 - t) * t * t * control2.x + t * t * t *
      destination.x;
                vertices[i].y = powf(1 - t, 3) * origin.y + 3.0f * powf(1 - t,
      2) * t * control1.y + 3.0f * (1 - t) * t * t * control2.y + t * t * t *
      destination.y;
                t += 1.0f / segments;
        
        vertices[segments] = (ccVertex2F) destination.x, destination.y;
        [shader_ use];
        [shader_ setUniformsForBuiltins];
        [shader_ setUniformLocation:colorLocation_ with4fv:(GLfloat*) &color_.r
       count:1];
        ccGLEnableVertexAttribs(kCCVertexAttribFlag_Position);
        glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT, GL_FALSE,
      0, vertices);
        glDrawArrays(GL_LINE_STRIP, 0, (GLsizei) segments + 1);
        
        CC_INCREMENT_GL_DRAWS(1);
void ccDrawLine (CGPoint origin, CGPoint destination)
draws a line given the origin and destination point measured in points.
Referenced by ccDrawLine(), and ccDrawRect().
        lazy_init();
        ccVertex2F vertices[2] =
                origin.x, origin.y,
                destination.x, destination.y
        ;
        [shader_ use];
        [shader_ setUniformsForBuiltins];
        [shader_ setUniformLocation:colorLocation_ with4fv:(GLfloat*) &color_.r
       count:1];
        ccGLEnableVertexAttribs(kCCVertexAttribFlag_Position);
        glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT, GL_FALSE,
      0, vertices);
        glDrawArrays(GL_LINES, 0, 2);
        
        CC_INCREMENT_GL_DRAWS(1);
void ccDrawPoint (CGPoint point)
draws a point given x and y coordinate measured in points.
Referenced by ccDrawPoint().
        lazy_init();
        ccVertex2F p = (ccVertex2F) point.x, point.y;
        ccGLEnableVertexAttribs(kCCVertexAttribFlag_Position);
        [shader_ use];
        [shader_ setUniformsForBuiltins];
        [shader_ setUniformLocation:colorLocation_ with4fv:(GLfloat*) &color_.r
       count:1];
        [shader_ setUniformLocation:pointSizeLocation_ withF1:pointSize_];
        glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT, GL_FALSE,
      0, &p);
        glDrawArrays(GL_POINTS, 0, 1);
        
        CC_INCREMENT_GL_DRAWS(1);
void ccDrawPoints (const CGPoint * points, NSUInteger numberOfPoints)
draws an array of points.
Since
v0.7.2
Referenced by ccDrawPoints().
        lazy_init();
        ccGLEnableVertexAttribs(kCCVertexAttribFlag_Position);
        [shader_ use];
        [shader_ setUniformsForBuiltins];
        [shader_ setUniformLocation:colorLocation_ with4fv:(GLfloat*) &color_.r
       count:1];
        [shader_ setUniformLocation:pointSizeLocation_ withF1:pointSize_];
        // XXX: Mac OpenGL error. arrays can't go out of scope before draw is
       executed
        ccVertex2F newPoints[numberOfPoints];
        // iPhone and 32-bit machines optimization
        if(sizeof(CGPoint) == sizeof(ccVertex2F))
                glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT,
      GL_FALSE, 0, points);
        else
    
                // Mac on 64-bit
                for(NSUInteger i=0; i<numberOfPoints;i++)
                        newPoints[i] = (ccVertex2F) points[i].x, points[i].y
      ;
                glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT,
      GL_FALSE, 0, newPoints);
        
    glDrawArrays(GL_POINTS, 0, (GLsizei) numberOfPoints);
        
        CC_INCREMENT_GL_DRAWS(1);
void ccDrawPoly (const CGPoint * vertices, NSUInteger numOfVertices, BOOL closePolygon)
draws a polygon given a pointer to CGPoint coordinates and the number of vertices measured in points. The polygon can be closed or open
Referenced by ccDrawPoly(), and CCSprite::updateTransform.
        lazy_init();
        [shader_ use];
        [shader_ setUniformsForBuiltins];
        [shader_ setUniformLocation:colorLocation_ with4fv:(GLfloat*) &color_.r
       count:1];
        ccGLEnableVertexAttribs(kCCVertexAttribFlag_Position);
        // XXX: Mac OpenGL error. arrays can't go out of scope before draw is
       executed
        ccVertex2F newPoli[numberOfPoints];
        // iPhone and 32-bit machines optimization
        if(sizeof(CGPoint) == sizeof(ccVertex2F))
                glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT,
      GL_FALSE, 0, poli);
        else
    
                // Mac on 64-bit
                for(NSUInteger i=0; i<numberOfPoints;i++)
                        newPoli[i] = (ccVertex2F) poli[i].x, poli[i].y ;
                glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT,
      GL_FALSE, 0, newPoli);
        
        if(closePolygon)
                glDrawArrays(GL_LINE_LOOP, 0, (GLsizei) numberOfPoints);
        else
                glDrawArrays(GL_LINE_STRIP, 0, (GLsizei) numberOfPoints);
        
        CC_INCREMENT_GL_DRAWS(1);
void ccDrawQuadBezier (CGPoint origin, CGPoint control, CGPoint destination, NSUInteger segments)
draws a quad bezier path measured in points.
Warning
This function could be pretty slow. Use it only for debugging purposes.
Since
v0.8
Referenced by ccDrawQuadBezier().
        lazy_init();
        ccVertex2F vertices[segments + 1];
        float t = 0.0f;
        for(NSUInteger i = 0; i < segments; i++)
        
                vertices[i].x = powf(1 - t, 2) * origin.x + 2.0f * (1 - t) * t
      * control.x + t * t * destination.x;
                vertices[i].y = powf(1 - t, 2) * origin.y + 2.0f * (1 - t) * t
      * control.y + t * t * destination.y;
                t += 1.0f / segments;
        
        vertices[segments] = (ccVertex2F) destination.x, destination.y;
        [shader_ use];
        [shader_ setUniformsForBuiltins];
        [shader_ setUniformLocation:colorLocation_ with4fv:(GLfloat*) &color_.r
       count:1];
        ccGLEnableVertexAttribs(kCCVertexAttribFlag_Position);
        glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT, GL_FALSE,
      0, vertices);
        glDrawArrays(GL_LINE_STRIP, 0, (GLsizei) segments + 1);
        
        CC_INCREMENT_GL_DRAWS(1);
void ccDrawRect (CGPoint origin, CGPoint destination)
draws a rectangle given the origin and destination point measured in points.
Referenced by ccDrawRect().
        ccDrawLine(CGPointMake(origin.x, origin.y), CGPointMake(destination.x,
      origin.y));
        ccDrawLine(CGPointMake(destination.x, origin.y), CGPointMake(
      destination.x, destination.y));
        ccDrawLine(CGPointMake(destination.x, destination.y), CGPointMake(
      origin.x, destination.y));
        ccDrawLine(CGPointMake(origin.x, destination.y), CGPointMake(origin.x,
      origin.y));
void ccDrawSolidPoly (const CGPoint * poli, NSUInteger numberOfPoints, ccColor4F color)
draws a solid polygon given a pointer to CGPoint coordinates, the number of vertices measured in points, and a color.
Referenced by ccDrawSolidPoly(), and ccDrawSolidRect().
        lazy_init();
    
        [shader_ use];
        [shader_ setUniformsForBuiltins];
        [shader_ setUniformLocation:colorLocation_ with4fv:(GLfloat*) &color.r
      count:1];
        ccGLEnableVertexAttribs(kCCVertexAttribFlag_Position);
        // XXX: Mac OpenGL error. arrays can't go out of scope before draw is
       executed
        ccVertex2F newPoli[numberOfPoints];
        // iPhone and 32-bit machines optimization
        if(sizeof(CGPoint) == sizeof(ccVertex2F))
                glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT,
      GL_FALSE, 0, poli);
        
        else
    
                // Mac on 64-bit
                for(NSUInteger i=0; i<numberOfPoints;i++)
                        newPoli[i] = (ccVertex2F) poli[i].x, poli[i].y ;
                
                glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT,
      GL_FALSE, 0, newPoli);
        
    
        glDrawArrays(GL_TRIANGLE_FAN, 0, (GLsizei) numberOfPoints);
void ccDrawSolidRect (CGPoint origin, CGPoint destination, ccColor4F color)
draws a solid rectangle given the origin and destination point measured in points.
Since
1.1
Referenced by ccDrawSolidRect().
        CGPoint vertices[] =
                origin,
                destination.x, origin.y,
                destination,
                origin.x, destination.y,
        ;
        
        ccDrawSolidPoly(vertices, 4, color);
void ccPointSize (GLfloat pointSize)
set the point size in points. Default 1.
Since
v2.0
Referenced by ccPointSize().
        pointSize_ = pointSize * CC_CONTENT_SCALE_FACTOR();
#ifdef __CC_PLATFORM_IOS
#elif defined(__CC_PLATFORM_MAC)
        glPointSize(pointSize);
#endif