/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/cocos2d/Support/CGPointExtension.h File Reference
#import `ccMacros.h`
*
#import <math.h>
*
#import <objc/objc.h>
*
Functions
CGFloat ccpLength (const CGPoint v)
CGFloat ccpDistance (const CGPoint v1, const CGPoint v2)
CGPoint ccpNormalize (const CGPoint v)
CGPoint ccpForAngle (const CGFloat a)
CGFloat ccpToAngle (const CGPoint v)
float clampf (float value, float min_inclusive, float max_inclusive)
CGPoint ccpClamp (CGPoint p, CGPoint from, CGPoint to)
CGPoint ccpFromSize (CGSize s)
CGPoint ccpCompOp (CGPoint p, float(*opFunc)(float))
CGPoint ccpLerp (CGPoint a, CGPoint b, float alpha)
BOOL ccpFuzzyEqual (CGPoint a, CGPoint b, float variance)
CGPoint ccpCompMult (CGPoint a, CGPoint b)
float ccpAngleSigned (CGPoint a, CGPoint b)
float ccpAngle (CGPoint a, CGPoint b)
CGPoint ccpRotateByAngle (CGPoint v, CGPoint pivot, float angle)
BOOL ccpLineIntersect (CGPoint p1, CGPoint p2, CGPoint p3, CGPoint p4, float *s, float *t)
BOOL ccpSegmentIntersect (CGPoint A, CGPoint B, CGPoint C, CGPoint D)
CGPoint ccpIntersectPoint (CGPoint A, CGPoint B, CGPoint C, CGPoint D)
Detailed Description
CGPoint extensions based on Chipmunk's cpVect file. These extensions work both with CGPoint and cpVect.
The `ccp` prefix means: `CoCos2d Point`
Examples:
ccpAdd(ccp(1,1), ccp(2,2)); // preferred cocos2d way
ccpAdd(CGPointMake(1,1), CGPointMake(2,2)); // also ok but more verbose
cpvadd(cpv(1,1), cpv(2,2)); // way of the chipmunk
ccpAdd(cpv(1,1), cpv(2,2)); // mixing chipmunk and cocos2d (avoid)
cpvadd(CGPointMake(1,1), CGPointMake(2,2)); // mixing chipmunk and CG (avoid)
Function Documentation
float ccpAngle (CGPoint a, CGPoint b)
Returns
the angle in radians between two vector directions
Since
v0.99.1
Referenced by ccpAngle().
        float angle = acosf(ccpDot(ccpNormalize(a), ccpNormalize(b)));
        if(fabs(angle) < kCGPointEpsilon) return 0.f;
        return angle;
float ccpAngleSigned (CGPoint a, CGPoint b)
Returns
the signed angle in radians between two vector directions
Since
v0.99.1
Referenced by ccpAngleSigned().
        CGPoint a2 = ccpNormalize(a);
        CGPoint b2 = ccpNormalize(b);
        float angle = atan2f(a2.x * b2.y - a2.y * b2.x, ccpDot(a2, b2));
        if(fabs(angle) < kCGPointEpsilon) return 0.f;
        return angle;
CGPoint ccpClamp (CGPoint p, CGPoint from, CGPoint to)
Clamp a point between from and to.
Since
v0.99.1
Referenced by ccpClamp().
        return ccp(clampf(p.x,min_inclusive.x,max_inclusive.x), clampf(p.y,
      min_inclusive.y, max_inclusive.y));
CGPoint ccpCompMult (CGPoint a, CGPoint b)
Multiplies a nd b components, a.x*b.x, a.y*b.y
Returns
a component-wise multiplication
Since
v0.99.1
Referenced by ccpCompMult().
        return ccp(a.x * b.x, a.y * b.y);
CGPoint ccpCompOp (CGPoint p, float(*)(float) opFunc)
Run a math operation function on each point component absf, fllorf, ceilf, roundf any function that has the signature: float func(float); For example: let's try to take the floor of x,y ccpCompOp(p,floorf);
Since
v0.99.1
Referenced by ccpCompOp().
        return ccp(opFunc(p.x), opFunc(p.y));
CGFloat ccpDistance (const CGPoint v1, const CGPoint v2)
Calculates the distance between two points
Returns
CGFloat
Since
v0.7.2
Referenced by ccpDistance().
        return ccpLength(ccpSub(v1, v2));
CGPoint ccpForAngle (const CGFloat a)
Converts radians to a normalized vector.
Returns
CGPoint
Since
v0.7.2
Referenced by ccpForAngle().
        return ccp(cosf(a), sinf(a));
CGPoint ccpFromSize (CGSize s)
Quickly convert CGSize to a CGPoint
Since
v0.99.1
Referenced by ccpFromSize().
        return ccp(s.width, s.height);
BOOL ccpFuzzyEqual (CGPoint a, CGPoint b, float variance)
Returns
if points have fuzzy equality which means equal with some degree of variance.
Since
v0.99.1
Referenced by ccpFuzzyEqual().
        if(a.x - var <= b.x && b.x <= a.x + var)
                if(a.y - var <= b.y && b.y <= a.y + var)
                        return true;
        return false;
CGFloat ccpLength (const CGPoint v)
Calculates distance between point an origin
Returns
CGFloat
Since
v0.7.2
Referenced by ccpDistance(), ccpLength(), and ccpNormalize().
        return sqrtf(ccpLengthSQ(v));
CGPoint ccpLerp (CGPoint a, CGPoint b, float alpha)
Linear Interpolation between two points a and b
Returns
alpha == 0 ? a alpha == 1 ? b otherwise a value between a..b
Since
v0.99.1
Referenced by ccpLerp().
        return ccpAdd(ccpMult(a, 1.f - alpha), ccpMult(b, alpha));
BOOL ccpLineIntersect (CGPoint p1, CGPoint p2, CGPoint p3, CGPoint p4, float * s, float * t)
A general line-line intersection test
Parameters
p1 is the startpoint for the first line P1 = (p1 - p2)
p2 is the endpoint for the first line P1 = (p1 - p2)
p3 is the startpoint for the second line P2 = (p3 - p4)
p4 is the endpoint for the second line P2 = (p3 - p4)
s is the range for a hitpoint in P1 (pa = p1 + s*(p2 - p1))
t is the range for a hitpoint in P3 (pa = p2 + t*(p4 - p3))
Returns
bool indicating successful intersection of a line note that to truly test intersection for segments we have to make sure that s & t lie within [0..1] and for rays, make sure s & t > 0 the hit point is p3 + t * (p4 - p3); the hit point also is p1 + s * (p2 - p1);
Since
v0.99.1
Referenced by ccpLineIntersect().
        // FAIL: Line undefined
        if ((A.x==B.x && A.y==B.y) || (C.x==D.x && C.y==D.y)) return NO;
        const float BAx = B.x - A.x;
        const float BAy = B.y - A.y;
        const float DCx = D.x - C.x;
        const float DCy = D.y - C.y;
        const float ACx = A.x - C.x;
        const float ACy = A.y - C.y;
        const float denom = DCy*BAx - DCx*BAy;
        *S = DCx*ACy - DCy*ACx;
        *T = BAx*ACy - BAy*ACx;
        if (denom == 0)
                if (*S == 0 || *T == 0)
                        // Lines incident
                        return YES;
                
                // Lines parallel and not incident
                return NO;
        
        *S = *S / denom;
        *T = *T / denom;
        // Point of intersection
        // CGPoint P;
        // P.x = A.x + *S * (B.x - A.x);
        // P.y = A.y + *S * (B.y - A.y);
        return YES;
CGPoint ccpNormalize (const CGPoint v)
Returns point multiplied to a length of 1.
Returns
CGPoint
Since
v0.7.2
Referenced by ccpAngle(), ccpAngleSigned(), ccpNormalize(), ccVertexLineToPolygon(), and CCParticleSystem::update:.
        return ccpMult(v, 1.0f/ccpLength(v));
CGPoint ccpRotateByAngle (CGPoint v, CGPoint pivot, float angle)
Rotates a point counter clockwise by the angle around a pivot
Parameters
v is the point to rotate
pivot is the pivot, naturally
angle is the angle of rotation cw in radians
Returns
the rotated point
Since
v0.99.1
Referenced by ccpRotateByAngle().
        CGPoint r = ccpSub(v, pivot);
        float cosa = cosf(angle), sina = sinf(angle);
        float t = r.x;
        r.x = t*cosa - r.y*sina + pivot.x;
        r.y = t*sina + r.y*cosa + pivot.y;
        return r;
CGFloat ccpToAngle (const CGPoint v)
Converts a vector to radians.
Returns
CGFloat
Since
v0.7.2
Referenced by ccpToAngle().
        return atan2f(v.y, v.x);
float clampf (float value, float min_inclusive, float max_inclusive)
Clamp a value between from and to.
Since
v0.99.1
Referenced by ccpClamp(), and clampf().
        if (min_inclusive > max_inclusive)
                CC_SWAP(min_inclusive,max_inclusive);
        
        return value < min_inclusive ? min_inclusive : value < max_inclusive?
      value : max_inclusive;