/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/cocos2d/Support/ZipUtils.h File Reference
#import <stdint.h>
*
Classes
struct CCZHeader
Enumerations
enum { CCZ_COMPRESSION_ZLIB,
CCZ_COMPRESSION_BZIP2,
CCZ_COMPRESSION_GZIP,
CCZ_COMPRESSION_NONE
 }
Functions
int ccInflateMemory (unsigned char *in, unsigned int inLength, unsigned char **out)
int ccInflateMemoryWithHint (unsigned char *in, unsigned int inLength, unsigned char **out, unsigned int outLenghtHint)
int ccInflateGZipFile (const char *filename, unsigned char **out)
int ccInflateCCZFile (const char *filename, unsigned char **out)
Detailed Description
Zip helper functions
Function Documentation
int ccInflateCCZFile (const char * filename, unsigned char ** out)
inflates a CCZ file into memory
Returns
the length of the deflated buffer
Since
v0.99.5
Referenced by ccInflateCCZFile(), and CCTexturePVR::initWithContentsOfFile:.
        NSCAssert(out, @"ccInflateCCZFile: invalid 'out' parameter");
        NSCAssert(&*out, @"ccInflateCCZFile: invalid 'out' parameter");
        // load file into memory
        unsigned char *compressed = NULL;
        NSInteger fileLen = ccLoadFileIntoMemory(path, &compressed);
        if(fileLen < 0)
                CCLOG(@"cocos2d: Error loading CCZ compressed file");
                return -1;
        
        struct CCZHeader *header = (struct CCZHeader*) compressed;
        // verify header
        if(header->sig[0] != 'C' || header->sig[1] != 'C' || header->sig[2] !=
       'Z' || header->sig[3] != '!')
                CCLOG(@"cocos2d: Invalid CCZ file");
                free(compressed);
                return -1;
        
        // verify header version
        uint16_t version = CFSwapInt16BigToHost(header->version);
        if(version > 2)
                CCLOG(@"cocos2d: Unsupported CCZ header format");
                free(compressed);
                return -1;
        
        // verify compression format
        if(CFSwapInt16BigToHost(header->compression_type) !=
      CCZ_COMPRESSION_ZLIB)
                CCLOG(@"cocos2d: CCZ Unsupported compression method");
                free(compressed);
                return -1;
        
        uint32_t len = CFSwapInt32BigToHost(header->len);
        *out = malloc(len);
        if(! *out)
        
                CCLOG(@"cocos2d: CCZ: Failed to allocate memory for texture");
                free(compressed);
                return -1;
        
        uLongf destlen = len;
        uLongf source = (uLongf) compressed + sizeof(*header);
        int ret = uncompress(*out, &destlen, (Bytef*)source, fileLen - sizeof(*
      header));
        free(compressed);
        if(ret != Z_OK)
        
                CCLOG(@"cocos2d: CCZ: Failed to uncompress data");
                free(*out);
                *out = NULL;
                return -1;
        
        return len;
int ccInflateGZipFile (const char * filename, unsigned char ** out)
inflates a GZip file into memory
Returns
the length of the deflated buffer
Since
v0.99.5
Referenced by ccInflateGZipFile(), and CCTexturePVR::initWithContentsOfFile:.
        int len;
        unsigned int offset = 0;
        NSCAssert(out, @"ccInflateGZipFile: invalid 'out' parameter");
        NSCAssert(&*out, @"ccInflateGZipFile: invalid 'out' parameter");
        gzFile inFile = gzopen(path, "rb");
        if(inFile == NULL)
                CCLOG(@"cocos2d: ZipUtils: error open gzip file: %s", path);
                return -1;
        
        /* 512k initial decompress buffer */
        int bufferSize = 512 * 1024;
        unsigned int totalBufferSize = bufferSize;
        *out = malloc(bufferSize);
        if(! out)
                CCLOG(@"cocos2d: ZipUtils: out of memory");
                return -1;
        
        for (;;)
                len = gzread(inFile, *out + offset, bufferSize);
                if (len < 0)
                        CCLOG(@"cocos2d: ZipUtils: error in gzread");
                        free(*out);
                        *out = NULL;
                        return -1;
                
                if (len == 0)
                        break;
                offset += len;
                // finish reading the file
                if(len < bufferSize)
                        break;
                bufferSize *= BUFFER_INC_FACTOR;
                totalBufferSize += bufferSize;
                unsigned char *tmp = realloc(*out, totalBufferSize);
                if(! tmp)
                        CCLOG(@"cocos2d: ZipUtils: out of memory");
                        free(*out);
                        *out = NULL;
                        return -1;
                
                *out = tmp;
        
        if (gzclose(inFile) != Z_OK)
                CCLOG(@"cocos2d: ZipUtils: gzclose failed");
        return offset;
int ccInflateMemory (unsigned char * in, unsigned int inLength, unsigned char ** out)
Inflates either zlib or gzip deflated memory. The inflated memory is expected to be freed by the caller.
It will allocate 256k for the destination buffer. If it is not enough it will multiply the previous buffer size per 2, until there is enough memory.
Returns
the length of the deflated buffer
Since
v0.8.1
Referenced by ccInflateMemory(), and CCParticleSystem::initWithDictionary:path:.
        // 256k for hint
        return ccInflateMemoryWithHint(in, inLength, out, 256 * 1024);
int ccInflateMemoryWithHint (unsigned char * in, unsigned int inLength, unsigned char ** out, unsigned int outLenghtHint)
Inflates either zlib or gzip deflated memory. The inflated memory is expected to be freed by the caller.
outLenghtHint is assumed to be the needed room to allocate the inflated buffer.
Returns
the length of the deflated buffer
Since
v1.0.0
Referenced by ccInflateMemory(), and ccInflateMemoryWithHint().
        unsigned int outLength = 0;
        int err = inflateMemoryWithHint(in, inLength, out, &outLength,
      outLengthHint);
        if (err != Z_OK || *out == NULL)
                if (err == Z_MEM_ERROR)
                        CCLOG(@"cocos2d: ZipUtils: Out of memory while
       decompressing map data!");
                else if (err == Z_VERSION_ERROR)
                        CCLOG(@"cocos2d: ZipUtils: Incompatible zlib version!")
      ;
                else if (err == Z_DATA_ERROR)
                        CCLOG(@"cocos2d: ZipUtils: Incorrect zlib compressed
       data!");
                else
                        CCLOG(@"cocos2d: ZipUtils: Unknown error while
       decompressing map data!");
                free(*out);
                *out = NULL;
                outLength = 0;
        
        return outLength;