/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/cocos2d/Support/ccCArray.h File Reference
#import <Foundation/Foundation.h>
*
#import <stdlib.h>
*
#import <string.h>
*
#import `../ccMacros.h`
*
Classes
struct ccArray
Defines
#define CCARRAYDATA_FOREACH(__array__, __object__) __object__=__array__->arr[0]; for(NSUInteger i=0, num=__array__->num; i<num; i++, __object__=__array__->arr[i])	\
Typedefs
typedef id CCARRAY_ID
typedef struct ccArray ccArray
typedef int(* cc_comparator)(const void *, const void *)
typedef ccArray ccCArray
Functions
ccArray * ccArrayNew (NSUInteger capacity)
void ccArrayFree (ccArray *arr)
void ccArrayDoubleCapacity (ccArray *arr)
void ccArrayEnsureExtraCapacity (ccArray *arr, NSUInteger extra)
void ccArrayShrink (ccArray *arr)
NSUInteger ccArrayGetIndexOfObject (ccArray *arr, id object)
BOOL ccArrayContainsObject (ccArray *arr, id object)
void ccArrayAppendObject (ccArray *arr, id object)
void ccArrayAppendObjectWithResize (ccArray *arr, id object)
void ccArrayAppendArray (ccArray *arr, ccArray *plusArr)
void ccArrayAppendArrayWithResize (ccArray *arr, ccArray *plusArr)
void ccArrayInsertObjectAtIndex (ccArray *arr, id object, NSUInteger index)
void ccArraySwapObjectsAtIndexes (ccArray *arr, NSUInteger index1, NSUInteger index2)
void ccArrayRemoveAllObjects (ccArray *arr)
void ccArrayRemoveObjectAtIndex (ccArray *arr, NSUInteger index)
void ccArrayFastRemoveObjectAtIndex (ccArray *arr, NSUInteger index)
void ccArrayFastRemoveObject (ccArray *arr, id object)
void ccArrayRemoveObject (ccArray *arr, id object)
void ccArrayRemoveArray (ccArray *arr, ccArray *minusArr)
void ccArrayFullRemoveArray (ccArray *arr, ccArray *minusArr)
void ccArrayMakeObjectsPerformSelector (ccArray *arr, SEL sel)
void ccArrayMakeObjectsPerformSelectorWithObject (ccArray *arr, SEL sel, id object)
void ccArrayMakeObjectPerformSelectorWithArrayObjects (ccArray *arr, SEL sel, id object)
ccCArray * ccCArrayNew (NSUInteger capacity)
void ccCArrayFree (ccCArray *arr)
void ccCArrayDoubleCapacity (ccCArray *arr)
void ccCArrayEnsureExtraCapacity (ccCArray *arr, NSUInteger extra)
NSUInteger ccCArrayGetIndexOfValue (ccCArray *arr, CCARRAY_ID value)
BOOL ccCArrayContainsValue (ccCArray *arr, CCARRAY_ID value)
void ccCArrayInsertValueAtIndex (ccCArray *arr, CCARRAY_ID value, NSUInteger index)
void ccCArrayAppendValue (ccCArray *arr, CCARRAY_ID value)
void ccCArrayAppendValueWithResize (ccCArray *arr, CCARRAY_ID value)
void ccCArrayAppendArray (ccCArray *arr, ccCArray *plusArr)
void ccCArrayAppendArrayWithResize (ccCArray *arr, ccCArray *plusArr)
void ccCArrayRemoveAllValues (ccCArray *arr)
void ccCArrayRemoveValueAtIndex (ccCArray *arr, NSUInteger index)
void ccCArrayFastRemoveValueAtIndex (ccCArray *arr, NSUInteger index)
void ccCArrayRemoveValue (ccCArray *arr, CCARRAY_ID value)
void ccCArrayRemoveArray (ccCArray *arr, ccCArray *minusArr)
void ccCArrayFullRemoveArray (ccCArray *arr, ccCArray *minusArr)
int cc_mergesortL (ccCArray *array, size_t width, cc_comparator comparator)
void cc_insertionSort (ccCArray *arr, cc_comparator comparator)
void cc_pointerswap (void *a, void *b, size_t width)
Detailed Description
based on Chipmunk cpArray. ccArray is a faster alternative to NSMutableArray, it does pretty much the same thing (stores NSObjects and retains/releases them appropriately). It's faster because:
it uses a plain C interface so it doesn't incur Objective-c messaging overhead
it assumes you know what you're doing, so it doesn't spend time on safety checks (index out of bounds, required capacity etc.)
comparisons are done using pointer equality instead of isEqual
There are 2 kind of functions:
ccArray functions that manipulates objective-c objects (retain and release are performed)
ccCArray functions that manipulates values like if they were standard C structures (no retain/release is performed)
Function Documentation
void ccArrayAppendArray (ccArray * arr, ccArray * plusArr)
Appends objects from plusArr to arr. Behavior undefined if arr doesn't have enough capacity.
Appends objects from plusArr to arr. Behaviour undefined if arr doesn't have enough capacity.
Referenced by ccArrayAppendArray(), and ccArrayAppendArrayWithResize().
        NSUInteger i;
        
        for(i = 0; i < plusArr->num; i++)
                ccArrayAppendObject(arr, plusArr->arr[i]);
void ccArrayAppendArrayWithResize (ccArray * arr, ccArray * plusArr)
Appends objects from plusArr to arr. Capacity of arr is increased if needed.
Referenced by ccArrayAppendArrayWithResize().
        ccArrayEnsureExtraCapacity(arr, plusArr->num);
        ccArrayAppendArray(arr, plusArr);
void ccArrayAppendObject (ccArray * arr, id object)
Appends an object. Behavior undefined if array doesn't have enough capacity.
Appends an object. Bahaviour undefined if array doesn't have enough capacity.
Referenced by CCActionManager::addAction:target:paused:, ccArrayAppendArray(), ccArrayAppendObject(), ccArrayAppendObjectWithResize(), CCScheduler::scheduleBlockForKey:target:interval:repeat:delay:paused:block:, and CCScheduler::scheduleSelector:forTarget:interval:repeat:delay:paused:.
        arr->arr[arr->num] = CC_ARC_RETAIN(object);
        arr->num++;
void ccArrayAppendObjectWithResize (ccArray * arr, id object)
Appends an object. Capacity of arr is increased if needed.
Referenced by CCParallaxNode::addChild:z:parallaxRatio:positionOffset:, and ccArrayAppendObjectWithResize().
        ccArrayEnsureExtraCapacity(arr, 1);
        ccArrayAppendObject(arr, object);
BOOL ccArrayContainsObject (ccArray * arr, id object)
Returns a Boolean value that indicates whether object is present in array.
Referenced by CCActionManager::addAction:target:paused:, ccArrayContainsObject(), ccArrayFullRemoveArray(), CCActionManager::removeAllActionsFromTarget:, and CCScheduler::unscheduleAllForTarget:.
        return ccArrayGetIndexOfObject(arr, object) != NSNotFound;
void ccArrayDoubleCapacity (ccArray * arr)
Doubles array capacity
Referenced by ccArrayDoubleCapacity(), ccArrayEnsureExtraCapacity(), and ccCArrayDoubleCapacity().
        arr->max *= 2;
        CCARRAY_ID *newArr = (CCARRAY_ID *)realloc(arr->arr, arr->max * sizeof
      (id));
        // will fail when there's not enough memory
    NSCAssert(newArr != NULL, @"ccArrayDoubleCapacity failed. Not enough memory
      ");
        arr->arr = newArr;
void ccArrayEnsureExtraCapacity (ccArray * arr, NSUInteger extra)
Increases array capacity such that max >= num + extra.
Referenced by ccArrayAppendArrayWithResize(), ccArrayAppendObjectWithResize(), ccArrayEnsureExtraCapacity(), ccArrayInsertObjectAtIndex(), ccCArrayEnsureExtraCapacity(), CCScheduler::scheduleBlockForKey:target:interval:repeat:delay:paused:block:, and CCScheduler::scheduleSelector:forTarget:interval:repeat:delay:paused:.
        while (arr->max < arr->num + extra)
                ccArrayDoubleCapacity(arr);
void ccArrayFastRemoveObjectAtIndex (ccArray * arr, NSUInteger index)
Removes object at specified index and fills the gap with the last object, thereby avoiding the need to push back subsequent objects. Behavior undefined if index outside [0, num-1].
Removes object at specified index and fills the gap with the last object, thereby avoiding the need to push back subsequent objects. Behaviour undefined if index outside [0, num-1].
Referenced by ccArrayFastRemoveObjectAtIndex().
        CC_ARC_RELEASE(arr->arr[index]);
        NSUInteger last = --arr->num;
        arr->arr[index] = arr->arr[last];
void ccArrayFree (ccArray * arr)
Frees array after removing all remaining objects. Silently ignores nil arr.
Referenced by ccArrayFree().
        if(arr == nil) return;
        
        ccArrayRemoveAllObjects(arr);
        
        free(arr->arr);
        free(arr);
void ccArrayFullRemoveArray (ccArray * arr, ccArray * minusArr)
Removes from arr all objects in minusArr. For each object in minusArr, all matching instances in arr will be removed.
Referenced by ccArrayFullRemoveArray().
        NSUInteger back = 0;
        NSUInteger i;
        
        for(i = 0; i < arr->num; i++)
                if(ccArrayContainsObject(minusArr, arr->arr[i]))
                        CC_ARC_RELEASE(arr->arr[i]);
                        back++;
                 else
                        arr->arr[i - back] = arr->arr[i];
        
        
        arr->num -= back;
NSUInteger ccArrayGetIndexOfObject (ccArray * arr, id object)
Returns index of first occurrence of object, NSNotFound if object not found.
Returns index of first occurence of object, NSNotFound if object not found.
Referenced by ccArrayContainsObject(), ccArrayGetIndexOfObject(), ccArrayRemoveObject(), and CCActionManager::removeAction:.
        NSUInteger i;
        
        for(i = 0; i < arr->num; i++)
                if(arr->arr[i] == object) return i;
        
        return NSNotFound;
void ccArrayInsertObjectAtIndex (ccArray * arr, id object, NSUInteger index)
Inserts an object at index
Referenced by ccArrayInsertObjectAtIndex(), and CCArray::replaceObjectAtIndex:withObject:.
        NSCAssert(index<=arr->num, @"Invalid index. Out of bounds");
        
        ccArrayEnsureExtraCapacity(arr, 1);
        
        NSUInteger remaining = arr->num - index;
        if(remaining > 0)
                memmove((void *)&arr->arr[index+1], (void *)&arr->arr[index],
      sizeof(id) * remaining);
        
        arr->arr[index] = CC_ARC_RETAIN(object);
        arr->num++;
void ccArrayMakeObjectsPerformSelector (ccArray * arr, SEL sel)
Sends to each object in arr the message identified by given selector.
Referenced by ccArrayMakeObjectsPerformSelector().
        NSUInteger i;
        
        for(i = 0; i < arr->num; i++)
#pragma clang diagnostic push
#if defined(__has_feature) && __has_feature(objc_arc)
#pragma clang diagnostic ignored "-Warc-performSelector-leaks"
#endif
                [arr->arr[i] performSelector:sel];
#pragma clang diagnostic pop
ccArray* ccArrayNew (NSUInteger capacity)
Allocates and initializes a new array with specified capacity
Referenced by ccArrayNew(), CCScheduler::scheduleBlockForKey:target:interval:repeat:delay:paused:block:, and CCScheduler::scheduleSelector:forTarget:interval:repeat:delay:paused:.
                                         
        if (capacity == 0)
                capacity = 1;
        
        ccArray *arr = (ccArray*)malloc(sizeof(ccArray));
        arr->num = 0;
        arr->arr = (CCARRAY_ID *)calloc(capacity, sizeof(id));
        arr->max = capacity;
        
        return arr;
void ccArrayRemoveAllObjects (ccArray * arr)
Removes all objects from arr
Referenced by ccArrayFree(), ccArrayRemoveAllObjects(), CCActionManager::removeAllActionsFromTarget:, and CCScheduler::unscheduleAllForTarget:.
        while(arr->num > 0)
                CC_ARC_RELEASE(arr->arr[--arr->num]);
void ccArrayRemoveArray (ccArray * arr, ccArray * minusArr)
Removes from arr all objects in minusArr. For each object in minusArr, the first matching instance in arr will be removed.
Referenced by ccArrayRemoveArray().
        NSUInteger i;
        
        for(i = 0; i < minusArr->num; i++)
                ccArrayRemoveObject(arr, minusArr->arr[i]);
void ccArrayRemoveObject (ccArray * arr, id object)
Searches for the first occurrence of object and removes it. If object is not found the function has no effect.
Searches for the first occurance of object and removes it. If object is not found the function has no effect.
Referenced by ccArrayRemoveArray(), and ccArrayRemoveObject().
        NSUInteger index = ccArrayGetIndexOfObject(arr, object);
        if (index != NSNotFound)
                ccArrayRemoveObjectAtIndex(arr, index);
void ccArrayRemoveObjectAtIndex (ccArray * arr, NSUInteger index)
Removes object at specified index and pushes back all subsequent objects. Behavior undefined if index outside [0, num-1].
Removes object at specified index and pushes back all subsequent objects. Behaviour undefined if index outside [0, num-1].
Referenced by ccArrayRemoveObject(), ccArrayRemoveObjectAtIndex(), CCArray::replaceObjectAtIndex:withObject:, CCScheduler::unscheduleBlockForKey:target:, and CCScheduler::unscheduleSelector:forTarget:.
        CC_ARC_RELEASE(arr->arr[index]);
        arr->num--;
        
        NSUInteger remaining = arr->num - index;
        if(remaining>0)
                memmove((void *)&arr->arr[index], (void *)&arr->arr[index+1],
      remaining * sizeof(id));
void ccArrayShrink (ccArray * arr)
shrinks the array so the memory footprint corresponds with the number of items
Referenced by ccArrayShrink().
    NSUInteger newSize;
        
        //only resize when necessary
        if (arr->max > arr->num && !(arr->num==0 && arr->max==1))
        
                if (arr->num!=0)
                
                        newSize=arr->num;
                        arr->max=arr->num;
                
                else
                //minimum capacity of 1, with 0 elements the array would be
       free'd by realloc
                        newSize=1;
                        arr->max=1;
                
                
                arr->arr = (CCARRAY_ID *) realloc(arr->arr,newSize * sizeof(id)
       );
                NSCAssert(arr->arr!=NULL,@"could not reallocate the memory");
        
void ccArraySwapObjectsAtIndexes (ccArray * arr, NSUInteger index1, NSUInteger index2)
Swaps two objects
Referenced by ccArraySwapObjectsAtIndexes().
        NSCAssert(index1 < arr->num, @"(1) Invalid index. Out of bounds");
        NSCAssert(index2 < arr->num, @"(2) Invalid index. Out of bounds");
        
        id object1 = arr->arr[index1];
        
        arr->arr[index1] = arr->arr[index2];
        arr->arr[index2] = object1;
void ccCArrayAppendArray (ccCArray * arr, ccCArray * plusArr)
Appends values from plusArr to arr. Behavior undefined if arr doesn't have enough capacity.
Appends values from plusArr to arr. Behaviour undefined if arr doesn't have enough capacity.
Referenced by ccCArrayAppendArray(), and ccCArrayAppendArrayWithResize().
        NSUInteger i;
        
        for(i = 0; i < plusArr->num; i++)
                ccCArrayAppendValue(arr, plusArr->arr[i]);
void ccCArrayAppendArrayWithResize (ccCArray * arr, ccCArray * plusArr)
Appends values from plusArr to arr. Capacity of arr is increased if needed.
Referenced by ccCArrayAppendArrayWithResize().
        ccCArrayEnsureExtraCapacity(arr, plusArr->num);
        ccCArrayAppendArray(arr, plusArr);
void ccCArrayAppendValue (ccCArray * arr, CCARRAY_ID value)
Appends an value. Behavior undefined if array doesn't have enough capacity.
Appends an value. Bahaviour undefined if array doesn't have enough capacity.
Referenced by ccCArrayAppendArray(), ccCArrayAppendValue(), and ccCArrayAppendValueWithResize().
        arr->arr[arr->num] = (id) value;
        arr->num++;
void ccCArrayAppendValueWithResize (ccCArray * arr, CCARRAY_ID value)
Appends an value. Capacity of arr is increased if needed.
Referenced by ccCArrayAppendValueWithResize().
        ccCArrayEnsureExtraCapacity(arr, 1);
        ccCArrayAppendValue(arr, value);
BOOL ccCArrayContainsValue (ccCArray * arr, CCARRAY_ID value)
Returns a Boolean value that indicates whether value is present in the C array.
Referenced by ccCArrayContainsValue(), and ccCArrayFullRemoveArray().
        return ccCArrayGetIndexOfValue(arr, value) != NSNotFound;
void ccCArrayDoubleCapacity (ccCArray * arr)
Doubles C array capacity
Referenced by ccCArrayDoubleCapacity().
        ccArrayDoubleCapacity(arr);
void ccCArrayEnsureExtraCapacity (ccCArray * arr, NSUInteger extra)
Increases array capacity such that max >= num + extra.
Referenced by ccCArrayAppendArrayWithResize(), ccCArrayAppendValueWithResize(), and ccCArrayEnsureExtraCapacity().
        ccArrayEnsureExtraCapacity(arr,extra);
void ccCArrayFastRemoveValueAtIndex (ccCArray * arr, NSUInteger index)
Removes value at specified index and fills the gap with the last value, thereby avoiding the need to push back subsequent values. Behavior undefined if index outside [0, num-1].
Since
v0.99.4
Removes value at specified index and fills the gap with the last value, thereby avoiding the need to push back subsequent values. Behaviour undefined if index outside [0, num-1].
Since
v0.99.4
Referenced by ccCArrayFastRemoveValueAtIndex().
        NSUInteger last = --arr->num;
        arr->arr[index] = arr->arr[last];
void ccCArrayFree (ccCArray * arr)
Frees C array after removing all remaining values. Silently ignores nil arr.
Referenced by ccCArrayFree(), and CCTMXLayer::releaseMap.
        if(arr == nil) return;
        
        ccCArrayRemoveAllValues(arr);
        
        free(arr->arr);
        free(arr);
void ccCArrayFullRemoveArray (ccCArray * arr, ccCArray * minusArr)
Removes from arr all values in minusArr. For each value in minusArr, all matching instances in arr will be removed.
Since
v0.99.4
Referenced by ccCArrayFullRemoveArray().
        NSUInteger i;
        NSUInteger back = 0;
        
        for(i = 0; i < arr->num; i++)
                if(ccCArrayContainsValue(minusArr, arr->arr[i]))
                        back++;
                 else
                        arr->arr[i - back] = arr->arr[i];
        
        
        arr->num -= back;
NSUInteger ccCArrayGetIndexOfValue (ccCArray * arr, CCARRAY_ID value)
Returns index of first occurrence of value, NSNotFound if value not found.
Returns index of first occurence of value, NSNotFound if value not found.
Referenced by ccCArrayContainsValue(), ccCArrayGetIndexOfValue(), and ccCArrayRemoveValue().
        NSUInteger i;
        
        for(i = 0; i < arr->num; i++)
                if([arr->arr[i] isEqual:value]) return i;
        return NSNotFound;
void ccCArrayInsertValueAtIndex (ccCArray * arr, CCARRAY_ID value, NSUInteger index)
Inserts a value at a certain position. Behavior undefined if array doesn't have enough capacity
Inserts a value at a certain position. Behaviour undefined if aray doesn't have enough capacity
Referenced by ccCArrayInsertValueAtIndex().
        NSCAssert(index < arr->max, @"ccCArrayInsertValueAtIndex: invalid
       index");
        
        NSUInteger remaining = arr->num - index;
        
        // last Value doesn't need to be moved
        if(remaining > 0)
                // tex coordinates
                memmove((void *)&arr->arr[index+1], (void *)&arr->arr[index],
      sizeof(void*) * remaining);
        
        
        arr->num++;
        arr->arr[index] = value;
ccCArray* ccCArrayNew (NSUInteger capacity)
Allocates and initializes a new C array with specified capacity
Referenced by ccCArrayNew(), and CCTMXLayer::initWithTilesetInfo:layerInfo:mapInfo:.
        if (capacity == 0)
                capacity = 1;
        
        ccCArray *arr = (ccCArray*)malloc(sizeof(ccCArray));
        arr->num = 0;
        arr->arr = (CCARRAY_ID *) malloc(capacity * sizeof(id));
        arr->max = capacity;
        
        return arr;
void ccCArrayRemoveAllValues (ccCArray * arr)
Removes all values from arr
Referenced by ccCArrayFree(), and ccCArrayRemoveAllValues().
        arr->num = 0;
void ccCArrayRemoveArray (ccCArray * arr, ccCArray * minusArr)
Removes from arr all values in minusArr. For each Value in minusArr, the first matching instance in arr will be removed.
Since
v0.99.4
Referenced by ccCArrayRemoveArray().
        NSUInteger i;
        
        for(i = 0; i < minusArr->num; i++)
                ccCArrayRemoveValue(arr, minusArr->arr[i]);
void ccCArrayRemoveValue (ccCArray * arr, CCARRAY_ID value)
Searches for the first occurrence of value and removes it. If value is not found the function has no effect.
Since
v0.99.4
Searches for the first occurance of value and removes it. If value is not found the function has no effect.
Since
v0.99.4
Referenced by ccCArrayRemoveArray(), and ccCArrayRemoveValue().
        NSUInteger index = ccCArrayGetIndexOfValue(arr, value);
        if (index != NSNotFound)
                ccCArrayRemoveValueAtIndex(arr, index);
void ccCArrayRemoveValueAtIndex (ccCArray * arr, NSUInteger index)
Removes value at specified index and pushes back all subsequent values. Behavior undefined if index outside [0, num-1].
Since
v0.99.4
Removes value at specified index and pushes back all subsequent values. Behaviour undefined if index outside [0, num-1].
Since
v0.99.4
Referenced by ccCArrayRemoveValue(), ccCArrayRemoveValueAtIndex(), and CCTMXLayer::removeTileAt:.
        NSUInteger last;
        
        for(last = --arr->num; index < last; index++)
                arr->arr[index] = arr->arr[index + 1];