/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/cocos2d/ccGLStateCache.h File Reference
#import <TargetConditionals.h>
*
#import `ccMacros.h`
*
#import `Platforms/CCGL.h`
*
Enumerations
enum {
*
kCCVertexAttribFlag_None = 0,
kCCVertexAttribFlag_Position = 1 << 0,
kCCVertexAttribFlag_Color = 1 << 1,
kCCVertexAttribFlag_TexCoords = 1 << 2,
*
kCCVertexAttribFlag_PosColorTex = (kCCVertexAttribFlag_Position | kCCVertexAttribFlag_Color | kCCVertexAttribFlag_TexCoords)
 }
enum ccGLServerState { CC_GL_ALL = 0
 }
Functions
void ccGLInvalidateStateCache (void)
void ccGLUseProgram (GLuint program)
void ccGLDeleteProgram (GLuint program)
void ccGLBlendFunc (GLenum sfactor, GLenum dfactor)
void ccGLBlendResetToCache (void)
void ccSetProjectionMatrixDirty (void)
void ccGLEnableVertexAttribs (unsigned int flags)
void ccGLBindTexture2D (GLuint textureId)
void ccGLBindTexture2DN (GLuint textureUnit, GLuint textureId)
void ccGLDeleteTexture (GLuint textureId)
void ccGLDeleteTextureN (GLuint textureUnit, GLuint textureId)
void ccGLBindVAO (GLuint vaoId)
void ccGLEnable (ccGLServerState flags)
Detailed Description
Enumeration Type Documentation
anonymous enum
vertex attrib flags
     
        kCCVertexAttribFlag_None = 0,
        
        kCCVertexAttribFlag_Position = 1 << 0,
        kCCVertexAttribFlag_Color = 1 << 1,
        kCCVertexAttribFlag_TexCoords = 1 << 2,
        
        kCCVertexAttribFlag_PosColorTex = (kCCVertexAttribFlag_Position |
      kCCVertexAttribFlag_Color | kCCVertexAttribFlag_TexCoords),
;
enum ccGLServerState
GL server side states
             
// CC_GL_SCISSOR_TEST = 1 << 0,
// CC_GL_STENCIL_TEST = 1 << 1,
// CC_GL_DEPTH_TEST = 1 << 2,
// CC_GL_BLEND = 1 << 3,
// CC_GL_DITHER = 1 << 4,
// CC_GL_ALL = (CC_GL_SCISSOR_TEST | CC_GL_STENCIL_TEST |
       CC_GL_DEPTH_TEST | CC_GL_BLEND | CC_GL_DITHER),
// CC_GL_ALL = (CC_GL_BLEND),
        CC_GL_ALL = 0,
        
 ccGLServerState;
Function Documentation
void ccGLBindTexture2D (GLuint textureId)
If the texture is not already bound to texture unit 0, it binds it. If CC_ENABLE_GL_STATE_CACHE is disabled, it will call glBindTexture() directly.
Since
v2.0.0
Referenced by ccGLBindTexture2D(), CCTextureAtlas::drawNumberOfQuads:fromIndex:, and CCTexture2D::initWithData:pixelFormat:pixelsWide:pixelsHigh:contentSize:.
        ccGLBindTexture2DN(0, textureId);
void ccGLBindTexture2DN (GLuint textureUnit, GLuint textureId)
If the texture is not already bound to a given unit, it binds it. If CC_ENABLE_GL_STATE_CACHE is disabled, it will call glBindTexture() directly.
Since
v2.1.0
Referenced by ccGLBindTexture2D(), and ccGLBindTexture2DN().
#if CC_ENABLE_GL_STATE_CACHE
        NSCAssert1(textureUnit < kCCMaxActiveTexture, @"cocos2d ERROR:
       Increase kCCMaxActiveTexture to %d!", textureUnit - GL_TEXTURE0);
        if(_ccCurrentBoundTexture[ textureUnit ] != textureId)
        
                _ccCurrentBoundTexture[ textureUnit ] = textureId;
                glActiveTexture(GL_TEXTURE0 + textureUnit);
                glBindTexture(GL_TEXTURE_2D, textureId);
        
#else
        glActiveTexture(GL_TEXTURE0 + textureUnit);
        glBindTexture(GL_TEXTURE_2D, textureId);
#endif
void ccGLBindVAO (GLuint vaoId)
If the vertex array is not already bound, it binds it. If CC_ENABLE_GL_STATE_CACHE is disabled, it will call glBindVertexArray() directly.
Since
v2.0.0
Referenced by ccGLBindVAO(), ccGLEnableVertexAttribs(), and CCTextureAtlas::drawNumberOfQuads:fromIndex:.
#if CC_ENABLE_GL_STATE_CACHE
        if(_ccVAO != vaoId)
        
                _ccVAO = vaoId;
                glBindVertexArray(vaoId);
        
#else
        glBindVertexArray(vaoId);
#endif
void ccGLBlendFunc (GLenum sfactor, GLenum dfactor)
Uses a blending function in case it not already used. If CC_ENABLE_GL_STATE_CACHE is disabled, it will the glBlendFunc() directly.
Since
v2.0.0
Referenced by ccGLBlendFunc(), and CCDirector::setAlphaBlending:.
#if CC_ENABLE_GL_STATE_CACHE
        if(sfactor != _ccBlendingSource || dfactor != _ccBlendingDest)
                _ccBlendingSource = sfactor;
                _ccBlendingDest = dfactor;
                SetBlending(sfactor, dfactor);
        
#else
        SetBlending(sfactor, dfactor);
#endif // CC_ENABLE_GL_STATE_CACHE
void ccGLBlendResetToCache (void)
Resets the blending mode back to the cached state in case you used glBlendFuncSeparate() or glBlendEquation(). If CC_ENABLE_GL_STATE_CACHE is disabled, it will just set the default blending mode using GL_FUNC_ADD.
Since
v2.0.0
Referenced by ccGLBlendResetToCache().
        glBlendEquation(GL_FUNC_ADD);
#if CC_ENABLE_GL_STATE_CACHE
        SetBlending(_ccBlendingSource, _ccBlendingDest);
#else
        SetBlending(CC_BLEND_SRC, CC_BLEND_DST);
#endif // CC_ENABLE_GL_STATE_CACHE
void ccGLDeleteProgram (GLuint program)
Deletes the GL program. If it is the one that is being used, it invalidates it. If CC_ENABLE_GL_STATE_CACHE is disabled, it will the glDeleteProgram() directly.
Since
v2.0.0
Referenced by ccGLDeleteProgram(), and CCGLProgram::link.
#if CC_ENABLE_GL_STATE_CACHE
        if(program == _ccCurrentShaderProgram)
                _ccCurrentShaderProgram = -1;
#endif // CC_ENABLE_GL_STATE_CACHE
        
        glDeleteProgram(program);
void ccGLDeleteTexture (GLuint textureId)
It will delete a given texture. If the texture was bound, it will invalidate the cached for texture unit 0. If CC_ENABLE_GL_STATE_CACHE is disabled, it will call glDeleteTextures() directly.
Since
v2.0.0
Referenced by ccGLDeleteTexture().
        ccGLDeleteTextureN(0, textureId);
void ccGLDeleteTextureN (GLuint textureUnit, GLuint textureId)
It will delete a given texture. If the texture was bound, it will invalidate the cached for the given texture unit. If CC_ENABLE_GL_STATE_CACHE is disabled, it will call glDeleteTextures() directly.
Since
v2.1.0
Referenced by ccGLDeleteTexture(), and ccGLDeleteTextureN().
#if CC_ENABLE_GL_STATE_CACHE
        if(_ccCurrentBoundTexture[ textureUnit ] == textureId)
                _ccCurrentBoundTexture[ textureUnit ] = -1;
#endif // CC_ENABLE_GL_STATE_CACHE
        glDeleteTextures(1, &textureId);
void ccGLEnable (ccGLServerState flags)
It will enable / disable the server side GL states. If CC_ENABLE_GL_STATE_CACHE is disabled, it will call glEnable() directly.
Since
v2.0.0
Referenced by ccGLEnable().
#if CC_ENABLE_GL_STATE_CACHE
        
// BOOL enabled = NO;
//
// /* GL_BLEND */
// if((enabled=(flags & CC_GL_BLEND)) != (_ccGLServerState & CC_GL_BLEND)
       )
// if(enabled)
// glEnable(GL_BLEND);
// _ccGLServerState |= CC_GL_BLEND;
// else
// glDisable(GL_BLEND);
// _ccGLServerState &= ~CC_GL_BLEND;
//
//
        
#else
// if(flags & CC_GL_BLEND)
// glEnable(GL_BLEND);
// else
// glDisable(GL_BLEND);
#endif
void ccGLEnableVertexAttribs (unsigned int flags)
Will enable the vertex attribs that are passed as flags. Possible flags:
kCCVertexAttribFlag_Position kCCVertexAttribFlag_Color kCCVertexAttribFlag_TexCoords
These flags can be ORed. The flags that are not present, will be disabled.
Since
v2.0.0
Referenced by ccDrawCardinalSpline(), ccDrawCircle(), ccDrawCubicBezier(), ccDrawLine(), ccDrawPoint(), ccDrawPoints(), ccDrawPoly(), ccDrawQuadBezier(), ccDrawSolidPoly(), ccGLEnableVertexAttribs(), and CCTextureAtlas::drawNumberOfQuads:fromIndex:.
        ccGLBindVAO(0);
        
        /* Position */
        BOOL enablePosition = flags & kCCVertexAttribFlag_Position;
        
        if(enablePosition != _vertexAttribPosition)
                if(enablePosition)
                        glEnableVertexAttribArray(kCCVertexAttrib_Position);
                else
                        glDisableVertexAttribArray(kCCVertexAttrib_Position);
                _vertexAttribPosition = enablePosition;
        
        /* Color */
        BOOL enableColor = flags & kCCVertexAttribFlag_Color;
        
        if(enableColor != _vertexAttribColor)
                if(enableColor)
                        glEnableVertexAttribArray(kCCVertexAttrib_Color);
                else
                        glDisableVertexAttribArray(kCCVertexAttrib_Color);
                _vertexAttribColor = enableColor;
        
        /* Tex Coords */
        BOOL enableTexCoords = flags & kCCVertexAttribFlag_TexCoords;
        
        if(enableTexCoords != _vertexAttribTexCoords)
                if(enableTexCoords)
                        glEnableVertexAttribArray(kCCVertexAttrib_TexCoords);
                else
                        glDisableVertexAttribArray(kCCVertexAttrib_TexCoords)
      ;
                _vertexAttribTexCoords = enableTexCoords;
        
void ccGLInvalidateStateCache (void)
Invalidates the GL state cache. If CC_ENABLE_GL_STATE_CACHE it will reset the GL state cache.
Since
v2.0.0
Referenced by ccGLInvalidateStateCache(), and CCDirector::end.
        kmGLFreeAll();
        
        _ccCurrentProjectionMatrix = -1;
        _vertexAttribPosition = NO;
        _vertexAttribColor = NO;
        _vertexAttribTexCoords = NO;
        
#if CC_ENABLE_GL_STATE_CACHE
        _ccCurrentShaderProgram = -1;
        for(NSInteger i=0; i < kCCMaxActiveTexture; i++)
                _ccCurrentBoundTexture[i] = -1;
        _ccBlendingSource = -1;
        _ccBlendingDest = -1;
        _ccGLServerState = 0;
#endif
void ccGLUseProgram (GLuint program)
Uses the GL program in case program is different than the current one. If CC_ENABLE_GL_STATE_CACHE is disabled, it will the glUseProgram() directly.
Since
v2.0.0
Referenced by ccGLUseProgram(), and CCGLProgram::use.
#if CC_ENABLE_GL_STATE_CACHE
        if(program != _ccCurrentShaderProgram)
                _ccCurrentShaderProgram = program;
                glUseProgram(program);
        
#else
        glUseProgram(program);
#endif // CC_ENABLE_GL_STATE_CACHE
void ccSetProjectionMatrixDirty (void)
sets the projection matrix as dirty
Since
v2.0.0
Referenced by ccSetProjectionMatrixDirty().
        _ccCurrentProjectionMatrix = -1;