generate_js_bindings.JSBGenerateOOFunctions Class Reference
Public Member Functions
def __init__
def is_oof_method
def is_manually_bound_oo_function
def create_files
def get_base_class
def get_name_for_oof
def sort_oo_classes
def get_oof_name
def generate_function_prefix
def generate_implementation_prefix
def generate_implementation_suffix
def generate_implementation_class_variables
def generate_implementation_class_constructor
def generate_implementation_class_destructor
def generate_implementation_class_method
def generate_implementation_class_methods
def generate_implementation_class_jsb
def generate_implementation_class
def generate_implementation
def generate_header
def generate_registration
def generate_bindings
Public Attributes
bound_methods
generating_OOF
fd_h
fd_mm
fd_registration
current_class_name
Detailed Description
Class that generate Object Oriented JS Bindings after C API
Member Function Documentation
def generate_js_bindings.JSBGenerateOOFunctions.generate_bindings (self)
Main entry point to generate the JS Bindings for the C functions
Reimplemented from generate_js_bindings.JSBGenerateFunctions.
    def generate_bindings(self):
        self.create_files()
        self.generate_implementation()
        self.generate_header()
        self.generate_registration()
#
#
# Main class for the Bindings
#
#
def generate_js_bindings.JSBGenerateOOFunctions.generate_header (self)
Generates the .h for the .mm file
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_bindings().
    def generate_header(self):
        '''Generates the .h for the .mm file'''
        template = 'extern JSObject *JSB_%s_object;JSClass
       *JSB_%s_class;JSB_%s_createClass(JSContext *cx, JSObject* globalObj, const char*
       name);'
        self.generate_autogenerate_prefix(self.fd_h)
        klasses = self.sort_oo_classes()
        for klass_name in klasses:
            self.fd_h.write(template % (klass_name, klass_name, klass_name))
        self.generate_autogenerate_suffix(self.fd_h)
def generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_class_methods (self, klass_name)
Generates the bindings for all the "methods"
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_class_methods().
    def generate_implementation_class_methods(self, klass_name):
        '''Generates the bindings for all the "methods"'''
        self.bound_methods[klass_name] = []
        for func in self.bs['signatures']['function']:
            name = func['name']
            if name in self.functions_to_bind and self.is_oof_method(klass_name
      , name) and not self.is_manually_bound_oo_function(klass_name, name):
                # XXX: this works in chipmunk because the "classes" has the
       'baseclass' at the end:
                # cpCircleShape (OK)
                # But it won't work in this case:
                # cpShapeCircle (Won't work).
                # XXX: Script needs to be improved
                try:
                    self.generate_implementation_class_method(klass_name, func)
                    self.bound_methods[klass_name].append(func)
                except ParseException, e:
                    sys.stderr.write('NOT OK: "%s" Error: %s' % (name, str(e)
      ))
def generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_prefix (self)
Generates include files
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_class_methods().
    def generate_implementation_prefix(self):
        '''Generates include files'''
        self.generate_function_mm_prefix()
def generate_js_bindings.JSBGenerateOOFunctions.generate_registration (self)
Generates the code that will register the clases into the JS VM
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_bindings().
    def generate_registration(self):
        '''Generates the code that will register the clases into the JS VM'''
        self.generate_autogenerate_prefix(self.fd_registration)
        klasses = self.sort_oo_classes()
        for klass_name in klasses:
            js_class_name = klass_name
            if klass_name.startswith(self.function_prefix):
                js_class_name = klass_name[len(self.function_prefix):]
            self.fd_registration.write('%s%s_createClass(_cx, %s, "%s");' % (
      PROXY_PREFIX, klass_name, self.namespace, js_class_name))
        self.generate_autogenerate_suffix(self.fd_registration)
def generate_js_bindings.JSBGenerateOOFunctions.get_base_class (self, klass_name)
returns the base class of a given class name
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_class_methods(), and generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_prefix().
    def get_base_class(self, klass_name):
        '''returns the base class of a given class name'''
        base_class = self.c_object_properties.get('base_class', None: None)
        base_class = base_class.keys()[0]
        classes = self.c_object_properties['classes']
        for k in classes:
            if k == klass_name:
                if classes[k] == None:
                    return base_class
                return classes[k]
def generate_js_bindings.JSBGenerateOOFunctions.get_name_for_oof (self, klass_name, func)
returns the JS function name, the native function name and the number of args
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_class_methods().
    def get_name_for_oof(self, klass_name, func):
        '''returns the JS function name, the native function name and the
       number of args'''
        name = func['name']
        js_name = name[len(klass_name):]
        js_name = uncapitalize(js_name)
        native_name = '%s%s_%s' % (PROXY_PREFIX, klass_name, js_name)
        args = self.get_number_of_arguments(func)
        args = max(0, args - 1)
        return js_name, native_name, args
def generate_js_bindings.JSBGenerateOOFunctions.get_oof_name (self, klass_name, func_name)
returns an Object Oriented Function name after a function name
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_prefix().
    def get_oof_name(self, klass_name, func_name):
        '''returns an Object Oriented Function name after a function name'''
        func_name = func_name[len(klass_name):]
        func_name = uncapitalize(func_name)
        return '%s_%s' % (klass_name, func_name)
def generate_js_bindings.JSBGenerateOOFunctions.is_manually_bound_oo_function (self, klass_name, func_name)
returns whether or not the method is manually bound
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_class_methods().
    def is_manually_bound_oo_function(self, klass_name, func_name):
        '''returns whether or not the method is manually bound'''
        return (klass_name in self.manual_bound_methods) and (func_name in
      self.manual_bound_methods[klass_name])
def generate_js_bindings.JSBGenerateOOFunctions.is_oof_method (self, klass_name, name)
returns whether or not name is a method of klass_name
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_class_methods().
    def is_oof_method(self, klass_name, name):
        '''returns whether or not name is a method of klass_name'''
        # Member of the class ?
        if not name.startswith(klass_name):
            return False
        # constructor ?
        constructor_suffix = self.c_object_properties['constructor_suffix'].
      keys()[0]
        const_name = '%s%s' % (klass_name, constructor_suffix)
        # Hack for Chipmunk. Supports: "cpShapeBoxNew2"
        if name.startswith(const_name):
            return False
        # destructor ?
        destructor_suffix = self.c_object_properties['destructor_suffix'].keys(
      )[0]
        if name == '%s%s' % (klass_name, destructor_suffix):
            return False
        # Only methods
        return True
def generate_js_bindings.JSBGenerateOOFunctions.sort_oo_classes (self)
returns a list of the OO function-classes to parse. Inheritance is taken into account. Base classes are returned first. Only supports 1 level of inheritance
Referenced by generate_js_bindings.JSBGenerateOOFunctions.generate_header(), generate_js_bindings.JSBGenerateOOFunctions.generate_implementation_class_methods(), and generate_js_bindings.JSBGenerateOOFunctions.generate_registration().
    def sort_oo_classes(self):
        """returns a list of the OO function-classes to parse. Inheritance is
       taken into account. Base classes are returned first. Only supports 1 level of
       inheritance"""
        tree =
        l = []
        for k in self.c_object_properties['classes']:
            v = self.c_object_properties['classes'][k]
            if not v in tree:
                tree[v] = []
            tree[v].append(k)
        # Start for orphan
        # XXX Only supports one level of inheritance. Good enough for Chipmunk
        orphans = tree[None]
        for k in orphans:
            l.append(k)
            if k in tree:
                for kk in tree[k]:
                    l.append(kk)
        return l
The documentation for this class was generated from the following file:
/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/external/jsbindings/generate_js_bindings.py