b2DynamicTree Class Reference
#include <b2DynamicTree.h>
Public Member Functions
b2DynamicTree ()
Constructing the tree initializes the node pool.
~b2DynamicTree ()
Destroy the tree, freeing the node pool.
int32 CreateProxy (const b2AABB &aabb, void *userData)
Create a proxy. Provide a tight fitting AABB and a userData pointer.
void DestroyProxy (int32 proxyId)
Destroy a proxy. This asserts if the id is invalid.
bool MoveProxy (int32 proxyId, const b2AABB &aabb1, const b2Vec2 &displacement)
void * GetUserData (int32 proxyId) const
const b2AABB & GetFatAABB (int32 proxyId) const
Get the fat AABB for a proxy.
template<typename T >
void Query (T *callback, const b2AABB &aabb) const
template<typename T >
void RayCast (T *callback, const b2RayCastInput &input) const
void Validate () const
Validate this tree. For testing.
int32 GetHeight () const
int32 GetMaxBalance () const
float32 GetAreaRatio () const
Get the ratio of the sum of the node areas to the root area.
void RebuildBottomUp ()
Build an optimal tree. Very expensive. For testing.
Detailed Description
A dynamic AABB tree broad-phase, inspired by Nathanael Presson's btDbvt. A dynamic tree arranges data in a binary tree to accelerate queries such as volume queries and ray casts. Leafs are proxies with an AABB. In the tree we expand the proxy AABB by b2_fatAABBFactor so that the proxy AABB is bigger than the client object. This allows the client object to move by small amounts without triggering a tree update.
Nodes are pooled and relocatable, so we use node indices rather than pointers.
Member Function Documentation
int32 b2DynamicTree::GetHeight () const
Compute the height of the binary tree in O(N) time. Should not be called often.
Referenced by b2BroadPhase::GetTreeHeight().
        if (m_root == b2_nullNode)
        
                return 0;
        
        return m_nodes[m_root].height;
int32 b2DynamicTree::GetMaxBalance () const
Get the maximum balance of an node in the tree. The balance is the difference in height of the two children of a node.
Referenced by b2BroadPhase::GetTreeBalance().
        int32 maxBalance = 0;
        for (int32 i = 0; i < m_nodeCapacity; ++i)
        
                const b2TreeNode* node = m_nodes + i;
                if (node->height <= 1)
                
                        continue;
                
                b2Assert(node->IsLeaf() == false);
                int32 child1 = node->child1;
                int32 child2 = node->child2;
                int32 balance = b2Abs(m_nodes[child2].height - m_nodes[child1].
      height);
                maxBalance = b2Max(maxBalance, balance);
        
        return maxBalance;
void * b2DynamicTree::GetUserData (int32 proxyId) const [inline]
Get proxy user data.
Returns
the proxy user data or 0 if the id is invalid.
Referenced by b2BroadPhase::GetUserData(), and b2BroadPhase::UpdatePairs().
        b2Assert(0 <= proxyId && proxyId < m_nodeCapacity);
        return m_nodes[proxyId].userData;
bool b2DynamicTree::MoveProxy (int32 proxyId, const b2AABB & aabb1, const b2Vec2 & displacement)
Move a proxy with a swepted AABB. If the proxy has moved outside of its fattened AABB, then the proxy is removed from the tree and re-inserted. Otherwise the function returns immediately.
Returns
true if the proxy was re-inserted.
        b2Assert(0 <= proxyId && proxyId < m_nodeCapacity);
        b2Assert(m_nodes[proxyId].IsLeaf());
        if (m_nodes[proxyId].aabb.Contains(aabb))
        
                return false;
        
        RemoveLeaf(proxyId);
        // Extend AABB.
        b2AABB b = aabb;
        b2Vec2 r(b2_aabbExtension, b2_aabbExtension);
        b.lowerBound = b.lowerBound - r;
        b.upperBound = b.upperBound + r;
        // Predict AABB displacement.
        b2Vec2 d = b2_aabbMultiplier * displacement;
        if (d.x < 0.0f)
        
                b.lowerBound.x += d.x;
        
        else
        
                b.upperBound.x += d.x;
        
        if (d.y < 0.0f)
        
                b.lowerBound.y += d.y;
        
        else
        
                b.upperBound.y += d.y;
        
        m_nodes[proxyId].aabb = b;
        InsertLeaf(proxyId);
        return true;
template<typename T > void b2DynamicTree::Query (T * callback, const b2AABB & aabb) const [inline]
Query an AABB for overlapping proxies. The callback class is called for each proxy that overlaps the supplied AABB.
Referenced by b2BroadPhase::Query(), and b2BroadPhase::UpdatePairs().
        b2GrowableStack<int32, 256> stack;
        stack.Push(m_root);
        while (stack.GetCount() > 0)
        
                int32 nodeId = stack.Pop();
                if (nodeId == b2_nullNode)
                
                        continue;
                
                const b2TreeNode* node = m_nodes + nodeId;
                if (b2TestOverlap(node->aabb, aabb))
                
                        if (node->IsLeaf())
                        
                                bool proceed = callback->QueryCallback(nodeId);
                                if (proceed == false)
                                
                                        return;
                                
                        
                        else
                        
                                stack.Push(node->child1);
                                stack.Push(node->child2);
                        
                
        
template<typename T > void b2DynamicTree::RayCast (T * callback, const b2RayCastInput & input) const [inline]
Ray-cast against the proxies in the tree. This relies on the callback to perform a exact ray-cast in the case were the proxy contains a shape. The callback also performs the any collision filtering. This has performance roughly equal to k * log(n), where k is the number of collisions and n is the number of proxies in the tree.
Parameters
input the ray-cast input data. The ray extends from p1 to p1 + maxFraction * (p2 - p1).
callback a callback class that is called for each proxy that is hit by the ray.
Referenced by b2BroadPhase::RayCast().
        b2Vec2 p1 = input.p1;
        b2Vec2 p2 = input.p2;
        b2Vec2 r = p2 - p1;
        b2Assert(r.LengthSquared() > 0.0f);
        r.Normalize();
        // v is perpendicular to the segment.
        b2Vec2 v = b2Cross(1.0f, r);
        b2Vec2 abs_v = b2Abs(v);
        // Separating axis for segment (Gino, p80).
        // |dot(v, p1 - c)| > dot(|v|, h)
        float32 maxFraction = input.maxFraction;
        // Build a bounding box for the segment.
        b2AABB segmentAABB;
        
                b2Vec2 t = p1 + maxFraction * (p2 - p1);
                segmentAABB.lowerBound = b2Min(p1, t);
                segmentAABB.upperBound = b2Max(p1, t);
        
        b2GrowableStack<int32, 256> stack;
        stack.Push(m_root);
        while (stack.GetCount() > 0)
        
                int32 nodeId = stack.Pop();
                if (nodeId == b2_nullNode)
                
                        continue;
                
                const b2TreeNode* node = m_nodes + nodeId;
                if (b2TestOverlap(node->aabb, segmentAABB) == false)
                
                        continue;
                
                // Separating axis for segment (Gino, p80).
                // |dot(v, p1 - c)| > dot(|v|, h)
                b2Vec2 c = node->aabb.GetCenter();
                b2Vec2 h = node->aabb.GetExtents();
                float32 separation = b2Abs(b2Dot(v, p1 - c)) - b2Dot(abs_v, h);
                if (separation > 0.0f)
                
                        continue;
                
                if (node->IsLeaf())
                
                        b2RayCastInput subInput;
                        subInput.p1 = input.p1;
                        subInput.p2 = input.p2;
                        subInput.maxFraction = maxFraction;
                        float32 value = callback->RayCastCallback(subInput,
      nodeId);
                        if (value == 0.0f)
                        
                                // The client has terminated the ray cast.
                                return;
                        
                        if (value > 0.0f)
                        
                                // Update segment bounding box.
                                maxFraction = value;
                                b2Vec2 t = p1 + maxFraction * (p2 - p1);
                                segmentAABB.lowerBound = b2Min(p1, t);
                                segmentAABB.upperBound = b2Max(p1, t);
                        
                
                else
                
                        stack.Push(node->child1);
                        stack.Push(node->child2);
                
        
The documentation for this class was generated from the following files:
/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/external/Box2d/Box2D/Collision/b2DynamicTree.h
/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/external/Box2d/Box2D/Collision/b2DynamicTree.cpp