cpPolyShape
Classes
struct cpSplittingPlane
struct cpPolyShape
Typedefs
typedef struct cpSplittingPlane cpSplittingPlane
typedef struct cpPolyShape cpPolyShape
Functions
cpPolyShape * cpPolyShapeAlloc (void)
Allocate a polygon shape.
cpPolyShape * cpPolyShapeInit (cpPolyShape *poly, cpBody *body, int numVerts, const cpVect *verts, cpVect offset)
cpShape * cpPolyShapeNew (cpBody *body, int numVerts, cpVect *verts, cpVect offset)
cpPolyShape * cpBoxShapeInit (cpPolyShape *poly, cpBody *body, cpFloat width, cpFloat height)
Initialize a box shaped polygon shape.
cpPolyShape * cpBoxShapeInit2 (cpPolyShape *poly, cpBody *body, cpBB box)
Initialize an offset box shaped polygon shape.
cpShape * cpBoxShapeNew (cpBody *body, cpFloat width, cpFloat height)
Allocate and initialize a box shaped polygon shape.
cpShape * cpBoxShapeNew2 (cpBody *body, cpBB box)
Allocate and initialize an offset box shaped polygon shape.
cpBool cpPolyValidate (const cpVect *verts, const int numVerts)
int cpPolyShapeGetNumVerts (cpShape *shape)
Get the number of verts in a polygon shape.
cpVect cpPolyShapeGetVert (cpShape *shape, int idx)
Get the ith vertex of a polygon shape.
Function Documentation
cpPolyShape* cpPolyShapeInit (cpPolyShape * poly, cpBody * body, int numVerts, const cpVect * verts, cpVect offset)
Initialize a polygon shape. A convex hull will be created from the vertexes.
Referenced by cpBoxShapeInit2(), and cpPolyShapeNew().
        setUpVerts(poly, numVerts, verts, offset);
        cpShapeInit((cpShape *)poly, &polyClass, body);
        return poly;
cpShape* cpPolyShapeNew (cpBody * body, int numVerts, cpVect * verts, cpVect offset)
Allocate and initialize a polygon shape. A convex hull will be created from the vertexes.
        return (cpShape *)cpPolyShapeInit(cpPolyShapeAlloc(), body, numVerts,
      verts, offset);
cpBool cpPolyValidate (const cpVect * verts, const int numVerts)
Check that a set of vertexes is convex and has a clockwise winding. NOTE: Due to floating point precision issues, hulls created with cpQuickHull() are not guaranteed to validate!
Referenced by cpConvexHull().
        for(int i=0; i<numVerts; i++)
                cpVect a = verts[i];
                cpVect b = verts[(i+1)%numVerts];
                cpVect c = verts[(i+2)%numVerts];
                
                if(cpvcross(cpvsub(b, a), cpvsub(c, a)) > 0.0f)
                        return cpFalse;
                
        
        
        return cpTrue;