CCGLProgram Class Reference
#import <CCGLProgram.h>
Public Member Functions
(id) - initWithVertexShaderByteArray:fragmentShaderByteArray:
(id) - initWithVertexShaderFilename:fragmentShaderFilename:
(void) - addAttribute:index:
(BOOL) - link
(void) - use
(void) - updateUniforms
(void) - setUniformLocation:withI1:
(void) - setUniformLocation:withF1:
(void) - setUniformLocation:withF1:f2:
(void) - setUniformLocation:withF1:f2:f3:
(void) - setUniformLocation:withF1:f2:f3:f4:
(void) - setUniformLocation:with2fv:count:
(void) - setUniformLocation:with3fv:count:
(void) - setUniformLocation:with4fv:count:
(void) - setUniformLocation:withMatrix4fv:count:
(void) - setUniformsForBuiltins
((__deprecated__) - __attribute__
(NSString *) - vertexShaderLog
(NSString *) - fragmentShaderLog
(NSString *) - programLog
Public Attributes
GLuint program_
GLuint vertShader_
GLuint fragShader_
GLint uniforms_ [kCCUniform_MAX]
BOOL usesTime_
Protected Attributes
struct _hashUniformEntry * hashForUniforms_
Properties
GLuint program
Detailed Description
CCGLProgram Class that implements a glProgram
Since
v2.0.0
Member Function Documentation
- ((__deprecated__) __attribute__
Deprecated alias for setUniformsForBuiltins
- (void) addAttribute: (NSString *) attributeName index:(GLuint) index
It will add a new attribute to the shader
Referenced by CCShaderCache::loadDefaultShaders.
                    :(NSString *)attributeName index:(GLuint)index
        glBindAttribLocation(program_,
                                                 index,
                                                 [attributeName UTF8String]);
- (NSString *) fragmentShaderLog
returns the fragmentShader error log
        return [self logForOpenGLObject:fragShader_
                                           infoCallback:(GLInfoFunction)&
      glGetShaderiv
                                                        logFunc:(GLLogFunction)
      &glGetShaderInfoLog];
- (id) initWithVertexShaderByteArray: (const GLchar*) vShaderByteArray fragmentShaderByteArray:(const GLchar*) fShaderByteArray
Initializes the CCGLProgram with a vertex and fragment with bytes array
Referenced by initWithVertexShaderFilename:fragmentShaderFilename:.
                                   :(const GLchar *)vShaderByteArray
      fragmentShaderByteArray:(const GLchar *)fShaderByteArray
    if ((self = [super init]))
    
        program_ = glCreateProgram();
                
                vertShader_ = fragShader_ = 0;
                
                if(vShaderByteArray)
                        
                        if (![self compileShader:&vertShader_
                                                                type:
      GL_VERTEX_SHADER
                                                   byteArray:vShaderByteArray]
      )
                                CCLOG(@"cocos2d: ERROR: Failed to compile
       vertex shader");
                
                
        // Create and compile fragment shader
                if(fShaderByteArray)
                        if (![self compileShader:&fragShader_
                                                                type:
      GL_FRAGMENT_SHADER
                                                   byteArray:fShaderByteArray]
      )
                                CCLOG(@"cocos2d: ERROR: Failed to compile
       fragment shader");
                
                
                if(vertShader_)
                        glAttachShader(program_, vertShader_);
                
                if(fragShader_)
                        glAttachShader(program_, fragShader_);
                
                hashForUniforms_ = NULL;
    
        
    return self;
- (id) initWithVertexShaderFilename: (NSString *) vShaderFilename fragmentShaderFilename:(NSString *) fShaderFilename
Initializes the CCGLProgram with a vertex and fragment with contents of filenames
                                  :(NSString *)vShaderFilename
      fragmentShaderFilename:(NSString *)fShaderFilename
        
        const GLchar * vertexSource = (GLchar*) [[NSString
      stringWithContentsOfFile:[[CCFileUtils sharedFileUtils] fullPathFromRelativePathIgnoringResolutions:
      vShaderFilename] encoding:NSUTF8StringEncoding error:nil] UTF8String];
        const GLchar * fragmentSource = (GLchar*) [[NSString
      stringWithContentsOfFile:[[CCFileUtils sharedFileUtils]
      fullPathFromRelativePathIgnoringResolutions:fShaderFilename] encoding:NSUTF8StringEncoding error:nil] UTF8String];
        return [self initWithVertexShaderByteArray:vertexSource
      fragmentShaderByteArray:fragmentSource];
- (BOOL) link
links the glProgram
Referenced by CCShaderCache::loadDefaultShaders.
    NSAssert(program_ != 0, @"Cannot link invalid program");
        
    GLint status = GL_TRUE;
    glLinkProgram(program_);
        
    if (vertShader_)
        glDeleteShader(vertShader_);
    if (fragShader_)
        glDeleteShader(fragShader_);
    vertShader_ = fragShader_ = 0;
        
#if DEBUG
    glGetProgramiv(program_, GL_LINK_STATUS, &status);
    NSString* log = self.programLog;
        
    if (status == GL_FALSE)
        NSLog(@"cocos2d: ERROR: Failed to link program: %i - %@", program_, log
      );
        ccGLDeleteProgram(program_);
        program_ = 0;
    
#endif
        
    return (status == GL_TRUE);
- (NSString *) programLog
returns the program error log
        return [self logForOpenGLObject:program_
                                           infoCallback:(GLInfoFunction)&
      glGetProgramiv
                                                        logFunc:(GLLogFunction)
      &glGetProgramInfoLog];
- (void) setUniformLocation: (GLint) location with2fv:(GLfloat*) floats count:(NSUInteger) numberOfArrays
calls glUniform2fv only if the values are different than the previous call for this same shader program.
                          :(GLint)location with2fv:(GLfloat*)floats count:(
      NSUInteger)numberOfArrays
        BOOL updated = [self updateUniformLocation:location withData:floats
      sizeOfData:sizeof(float)*2*numberOfArrays];
        
        if(updated)
                glUniform2fv((GLint)location, (GLsizei)numberOfArrays, floats
      );
- (void) setUniformLocation: (GLint) location with3fv:(GLfloat*) floats count:(NSUInteger) numberOfArrays
calls glUniform3fv only if the values are different than the previous call for this same shader program.
                          :(GLint)location with3fv:(GLfloat*)floats count:(
      NSUInteger)numberOfArrays
        BOOL updated = [self updateUniformLocation:location withData:floats
      sizeOfData:sizeof(float)*3*numberOfArrays];
        
        if(updated)
                glUniform3fv((GLint)location, (GLsizei)numberOfArrays, floats
      );
- (void) setUniformLocation: (GLint) location with4fv:(GLvoid*) floats count:(NSUInteger) numberOfArrays
calls glUniform4fv only if the values are different than the previous call for this same shader program.
Referenced by ccDrawCardinalSpline(), ccDrawCircle(), ccDrawCubicBezier(), ccDrawLine(), ccDrawPoint(), ccDrawPoints(), ccDrawPoly(), ccDrawQuadBezier(), and ccDrawSolidPoly().
                          :(GLint)location with4fv:(GLvoid*)floats count:(
      NSUInteger)numberOfArrays
        BOOL updated = [self updateUniformLocation:location withData:floats
      sizeOfData:sizeof(float)*4*numberOfArrays];
        
        if(updated)
                glUniform4fv((GLint)location, (GLsizei)numberOfArrays, floats
      );
- (void) setUniformLocation: (GLint) location withF1:(GLfloat) f1
calls glUniform1f only if the values are different than the previous call for this same shader program.
Referenced by ccDrawPoint(), and ccDrawPoints().
                          :(GLint)location withF1:(GLfloat)f1
        BOOL updated = [self updateUniformLocation:location withData:&f1
      sizeOfData:sizeof(f1)*1];
        
        if(updated)
                glUniform1f((GLint)location, f1);
- (void) setUniformLocation: (GLint) location withF1:(GLfloat) f1 f2:(GLfloat) f2
calls glUniform2f only if the values are different than the previous call for this same shader program.
                          :(GLint)location withF1:(GLfloat)f1 f2:(GLfloat)f2
        GLfloat floats[2] = f1,f2;
        BOOL updated = [self updateUniformLocation:location withData:floats
      sizeOfData:sizeof(floats)];
        
        if(updated)
                glUniform2f((GLint)location, f1, f2);
- (void) setUniformLocation: (GLint) location withF1:(GLfloat) f1 f2:(GLfloat) f2 f3:(GLfloat) f3
calls glUniform3f only if the values are different than the previous call for this same shader program.
                          :(GLint)location withF1:(GLfloat)f1 f2:(GLfloat)f2 f3
      :(GLfloat)f3
        GLfloat floats[3] = f1,f2,f3;
        BOOL updated = [self updateUniformLocation:location withData:floats
      sizeOfData:sizeof(floats)];
        
        if(updated)
                glUniform3f((GLint)location, f1, f2, f3);
- (void) setUniformLocation: (GLint) location withF1:(GLfloat) f1 f2:(GLfloat) f2 f3:(GLfloat) f3 f4:(GLfloat) f4
calls glUniform4f only if the values are different than the previous call for this same shader program.
Referenced by GLESDebugDraw::DrawCircle(), GLESDebugDraw::DrawPolygon(), GLESDebugDraw::DrawSegment(), GLESDebugDraw::DrawSolidCircle(), GLESDebugDraw::DrawSolidPolygon(), and setUniformsForBuiltins.
                          :(GLint)location withF1:(GLfloat)f1 f2:(GLfloat)f2 f3
      :(GLfloat)f3 f4:(GLfloat)f4
        GLfloat floats[4] = f1,f2,f3,f4;
        BOOL updated = [self updateUniformLocation:location withData:floats
      sizeOfData:sizeof(floats)];
        
        if(updated)
                glUniform4f((GLint)location, f1, f2, f3,f4);
- (void) setUniformLocation: (GLint) location withI1:(GLint) i1
calls glUniform1i only if the values are different than the previous call for this same shader program.
Referenced by updateUniforms.
                          :(GLint)location withI1:(GLint)i1
        BOOL updated = [self updateUniformLocation:location withData:&i1
      sizeOfData:sizeof(i1)*1];
        
        if(updated)
                glUniform1i((GLint)location, i1);
- (void) setUniformLocation: (GLint) location withMatrix4fv:(GLvoid*) matrix_array count:(NSUInteger) numberOfMatrix
calls glUniformMatrix4fv only if the values are different than the previous call for this same shader program.
Referenced by setUniformsForBuiltins.
                          :(GLint)location withMatrix4fv:(GLvoid*)matrixArray
      count:(NSUInteger)numberOfMatrices
        BOOL updated = [self updateUniformLocation:location withData:
      matrixArray sizeOfData:sizeof(float)*16*numberOfMatrices];
        
        if(updated)
                glUniformMatrix4fv((GLint)location, (GLsizei)numberOfMatrices,
       GL_FALSE, matrixArray);
- (void) setUniformsForBuiltins
will update the builtin uniforms if they are different than the previous call for this same shader program.
Referenced by ccDrawCardinalSpline(), ccDrawCircle(), ccDrawCubicBezier(), ccDrawLine(), ccDrawPoint(), ccDrawPoints(), ccDrawPoly(), ccDrawQuadBezier(), and ccDrawSolidPoly().
        kmMat4 matrixP;
        kmMat4 matrixMV;
        kmMat4 matrixMVP;
        
        kmGLGetMatrix(KM_GL_PROJECTION, &matrixP);
        kmGLGetMatrix(KM_GL_MODELVIEW, &matrixMV);
        
        kmMat4Multiply(&matrixMVP, &matrixP, &matrixMV);
        
        [self setUniformLocation:uniforms_[ kCCUniformPMatrix] withMatrix4fv:
       matrixP.mat count:1];
        [self setUniformLocation:uniforms_[ kCCUniformMVMatrix] withMatrix4fv:
      matrixMV.mat count:1];
        [self setUniformLocation:uniforms_[kCCUniformMVPMatrix] withMatrix4fv:
      matrixMVP.mat count:1];
        
        if(usesTime_)
                CCDirector *director = [CCDirector sharedDirector];
                // This doesn't give the most accurate global time value.
                // Cocos2D doesn't store a high precision time value, so this
       will have to do.
                // Getting Mach time per frame per shader using time could be
       extremely expensive.
                ccTime time = director.totalFrames*director.animationInterval;
                
                [self setUniformLocation:uniforms_[kCCUniformTime] withF1:time/
      10.0 f2:time f3:time*2 f4:time*4];
                [self setUniformLocation:uniforms_[kCCUniformSinTime] withF1:
      sinf(time/8.0) f2:sinf(time/4.0) f3:sinf(time/2.0) f4:sinf(time)];
                [self setUniformLocation:uniforms_[kCCUniformCosTime] withF1:
      cosf(time/8.0) f2:cosf(time/4.0) f3:cosf(time/2.0) f4:cosf(time)];
        
        
        if(uniforms_[kCCUniformRandom01] != -1)
                [self setUniformLocation:uniforms_[kCCUniformRandom01] withF1:
      CCRANDOM_0_1() f2:CCRANDOM_0_1() f3:CCRANDOM_0_1() f4:CCRANDOM_0_1()];
        
- (void) updateUniforms
It will create 4 uniforms:
kCCUniformPMatrix
kCCUniformMVMatrix
kCCUniformMVPMatrix
kCCUniformSampler
And it will bind `kCCUniformSampler` to 0
Referenced by CCShaderCache::loadDefaultShaders.
        uniforms_[ kCCUniformPMatrix] = glGetUniformLocation(program_,
      kCCUniformPMatrix_s);
        uniforms_[ kCCUniformMVMatrix] = glGetUniformLocation(program_,
      kCCUniformMVMatrix_s);
        uniforms_[kCCUniformMVPMatrix] = glGetUniformLocation(program_,
      kCCUniformMVPMatrix_s);
        
        uniforms_[kCCUniformTime] = glGetUniformLocation(program_,
      kCCUniformTime_s);
        uniforms_[kCCUniformSinTime] = glGetUniformLocation(program_,
      kCCUniformSinTime_s);
        uniforms_[kCCUniformCosTime] = glGetUniformLocation(program_,
      kCCUniformCosTime_s);
        
        usesTime_ = (
                uniforms_[kCCUniformTime] != -1 ||
                uniforms_[kCCUniformSinTime] != -1 ||
                uniforms_[kCCUniformCosTime] != -1
        );
        uniforms_[kCCUniformRandom01] = glGetUniformLocation(program_,
      kCCUniformRandom01_s);
        
        uniforms_[kCCUniformSampler] = glGetUniformLocation(program_,
      kCCUniformSampler_s);
        [self use];
        
        // Since sample most probably won't change, set it to 0 now.
        [self setUniformLocation:uniforms_[kCCUniformSampler] withI1:0];
- (void) use
it will call glUseProgram()
Referenced by ccDrawCardinalSpline(), ccDrawCircle(), ccDrawCubicBezier(), ccDrawLine(), ccDrawPoint(), ccDrawPoints(), ccDrawPoly(), ccDrawQuadBezier(), ccDrawSolidPoly(), GLESDebugDraw::DrawCircle(), GLESDebugDraw::DrawPolygon(), GLESDebugDraw::DrawSegment(), GLESDebugDraw::DrawSolidCircle(), GLESDebugDraw::DrawSolidPolygon(), and updateUniforms.
        ccGLUseProgram(program_);
- (NSString *) vertexShaderLog
returns the vertexShader error log
        return [self logForOpenGLObject:vertShader_
                                           infoCallback:(GLInfoFunction)&
      glGetShaderiv
                                                        logFunc:(GLLogFunction)
      &glGetShaderInfoLog];
The documentation for this class was generated from the following files:
/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/cocos2d/CCGLProgram.h
/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/cocos2d/CCGLProgram.m