b2Rot Struct Reference
Rotation.
#include <b2Math.h>
Public Member Functions
b2Rot (float32 angle)
Initialize from an angle in radians.
void Set (float32 angle)
Set using an angle in radians.
void SetIdentity ()
Set to the identity rotation.
float32 GetAngle () const
Get the angle in radians.
b2Vec2 GetXAxis () const
Get the x-axis.
b2Vec2 GetYAxis () const
Get the u-axis.
Public Attributes
float32 s
Sine and cosine.
float32 c
Detailed Description
Rotation.
Constructor & Destructor Documentation
b2Rot::b2Rot (float32 angle) [inline, explicit]
Initialize from an angle in radians.
TODO_ERIN optimize
        
                s = sinf(angle);
                c = cosf(angle);
        
Member Function Documentation
void b2Rot::Set (float32 angle) [inline]
Set using an angle in radians.
TODO_ERIN optimize
Referenced by b2Sweep::GetTransform(), b2Transform::Set(), b2PolygonShape::SetAsBox(), and b2Body::SetTransform().
        
                s = sinf(angle);
                c = cosf(angle);
        
The documentation for this struct was generated from the following file:
/Bing/File/cocos2d/cocos2d-iphone/cocos2d-iphone-2.1-beta4/external/Box2d/Box2D/Common/b2Math.h